import figma, { html } from "@figma/code-connect/html"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/P6dLLqB92XEWLm2PoPISkY/SDS-Demo?node-id=9762-426&m=dev",
  {
    props: {
      hasIconStart: figma.boolean("Has Icon Start"),
      iconStart: figma.instance("Icon Start"),
      hasIconEnd: figma.boolean("Has Icon End"),
      iconEnd: figma.instance("Icon End"),
      label: figma.string("Label"),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Disabled: "disabled",
      }),
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
    },
    example: (props) => html`\
    <button 
    state =${props.state} 
    variant=${props.variant}
    size= ${props.size}
    (onClick)="onClick($event)"
    >
    
    ${props.label}
    
    </button>
   
    <script>
    export class Example {
    public onClick() {
    alert("You clicked ${props.label}");
      }
    }
    </script>`,
    imports: ["import { DsButton } from '@ds-angular/button'"],

    
  }
)
